export const ALL_EVENTS_REQUEST = 'ALL_EVENTS_REQUEST'
export  const ALL_EVENTS_FAIL = 'ALL_EVENTS_FAIL'
export  const ALL_EVENTS_SUCCESS = 'ALL_EVENTS_SUCCESS'  


export const EVENT_DETAILS_REQUEST = 'EVENT_DETAILS_REQUESTS'
export const EVENT_DETAILS_SUCCESS = 'EVENT_DETAILS_SUCCESS'
export const EVENT_DETAILS_FAIL = 'EVENT_DETAILS_FAIL'


export const ADMIN_EVENTS_REQUEST = 'ADMIN_EVENTS_REQUEST'
export  const ADMIN_EVENTS_FAIL = 'ADMIN_EVENTS_FAIL'
export  const ADMIN_EVENTS_SUCCESS = 'ADMIN_EVENTS_SUCCESS'  


export const NEW_EVENT_REQUEST = 'NEW_EVENT_REQUEST'
export const NEW_EVENT_SUCCESS = 'NEW_EVENT_SUCCESS'
export const NEW_EVENT_RESET = 'NEW_EVENT_RESET'
export const NEW_EVENT_FAIL = 'NEW_EVENT_FAIL'

export const DELETE_EVENT_REQUEST = 'DELETE_EVENT_REQUEST'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_RESET = 'DELETE_EVENT_RESET'
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL'

export const UPDATE_EVENT_REQUEST = 'UPDATE_EVENT_REQUEST'
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS'
export const UPDATE_EVENT_RESET = 'UPDATE_EVENT_RESET'
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
