export const CREATE_REGISTER_REQUEST = "CREATE_REGISTER_REQUEST" 
export const CREATE_REGISTER_SUCCESS = "CREATE_REGISTER_SUCCESS" 
export const CREATE_REGISTER_FAIL = "CREATE_REGISTER_FAIL" 


export const MY_REGISTER_REQUEST = "MY_REGISTER_REQUEST" 
export const MY_REGISTER_SUCCESS = "MY_REGISTER_SUCCESS" 
export const MY_REGISTER_FAIL = "MY_REGISTER_FAIL" 

export const ALL_REGISTER_REQUEST = "ALL_REGISTER_REQUEST" 
export const ALL_REGISTER_SUCCESS = "ALL_REGISTER_SUCCESS" 
export const ALL_REGISTER_FAIL = "ALL_REGISTER_FAIL" 

export const UPDATE_REGISTER_REQUEST = "UPDATE_REGISTER_REQUEST" 
export const UPDATE_REGISTER_SUCCESS = "UPDATE_REGISTER_SUCCESS" 
export const UPDATE_REGISTER_FAIL = "UPDATE_REGISTER_FAIL" 
export const UPDATE_REGISTER_RESET = 'UPDATE_REGISTER_RESET'

export const DELETE_REGISTER_REQUEST = "DELETE_REGISTER_REQUEST" 
export const DELETE_REGISTER_SUCCESS = "DELETE_REGISTER_SUCCESS" 
export const DELETE_REGISTER_FAIL = "DELETE_REGISTER_FAIL" 
export const DELETE_REGISTER_RESET = 'DELETE_REGISTER_RESET'


export const REGISTER_DETAIL_REQUEST = "REGISTER_DETAIL_REQUEST" 
export const REGISTER_DETAIL_SUCCESS = "REGISTER_DETAIL_SUCCESS" 
export const REGISTER_DETAIL_FAIL = "REGISTER_DETAIL_FAIL" 

export const CLEAR_ERRORS = 'CLEAR_ERRORS'